### ISSUE TITLE
New Tournament with Blunder included

### ISSUE THREAD

**Issue by GrahamCCRL** [algerbrex/blunder#11]
THE BLUNDER-BUSS RAMPAGE

Intel i7 Quad
ChessGUI
256mb hash each
3-4-5 piece tablebases
Ponder off
ICOfy2013HQ.cgb book
40 moves in 16 minutes repeating (adapted for the CCRL)
2 cycles 30 rounds
All engines 64-bit 1CPU (where available)

Participants

KnightX 3.1 64-bit
Blunder 7.6.0 64-bit
Protej 0.6.1 64-bit
Chess Tiger 2007.1
ECE 20.1 64-bit
RookieMonster 0.9.4 64-bit
Fridolin 3.10 64-bit
Supernova 2.4 64-bit
Zevra 2.5 64-bit
Odonata 0.5.1 64-bit
Chessmaster 9000
Raven 1.20 64-bit
Myrddin 0.88 64-bit
Capivara LK 0.09b02g 64-bit
Jumbo 0.7.0 64-bit
Qapla 0.1.1 64-bit

Games and standings will be available after every six rounds from the following link:
http://kirill-kryukov.com/chess/discussion-board/viewtopic.php?f=7&t=13697

Web based link for live viewing (huge thanks to Jay - Berserk author).
http://tlcv.net/16093

Alternatively, if you install TLCV (Tom's Live Chess Viewer) on your computer, you can watch the games live move by move. You'll also be able to chat to others following the tournament in the chatroom there.
http://kirill-kryukov.com/chess/discussion-board/download/file.php?id=42959
Host - GrahamCCRL.dyndns.org Port - 16093

Linux users can use Livius:
https://github.com/kmar/livius

There is also a Livius windows version.
It has live pv boards as a nice addition.
http://www.crabaware.com/livius/

**Comment by GrahamCCRL** [comment]
Thanks.
I didn't have your email address at the time, so that was the only way I
could let you know about the tournament. :-)

**Comment by algerbrex** [comment]
No problem at all, I appreciate the heads-up :-)
