### ISSUE TITLE
just win on the white squares

### ISSUE THREAD

**Issue by tissatussa** [algerbrex/blunder#13]
Lately i stumbled upon this typical position :

![diagram_f6](https://user-images.githubusercontent.com/1109281/148869646-781f8102-1316-417a-a9af-661e318f6b33.png)

White to move.
it's a position from one of the well known 15 test suites at https://sites.google.com/site/strategictestsuite/about-1 .. this is an old site and some links are broken, but here you can find all these 15 EPD files for download. In one of them was this EPD :

rk6/pP1p2p1/B7/3K1P2/8/8/7b/8 w - - bm f6;

yes, the move (here comes the spoiler) f6 is best !

the reason is simple : Black must take the pawn, so the White King can walk on the white squares and reach the backrow on the d file and after b7xa8 Kxa8 he can even come to c8 and give mate by the Bishop. The black squared Black Bishop can do nothing about this King walk, but most engines do not see this : their search may reach deep but the almost forced solution line seems over their horizon .. only one strong engine finds it : ShashChess, a special Stockfish version, based on the theory of Alexander Shashin, see https://github.com/amchess/ShashChess/ i used a python script which i'm developing since one month. Take a close look at this screencast - the displayed information of the data flow should tell a lot about how engines calculate :

_9 engines should find f6 !_
https://www.bitchute.com/video/u8weJhqR05gw/

and here's a short one with two Blunders : 

https://user-images.githubusercontent.com/1109281/148869723-da19727e-838d-4006-a3ec-45c149b129bf.mp4

hope you like the music !

i can elaborate about this position and the data flow you see in the screencasts.

so, the question is : why do most engines have no clue in this position or alike ?

**Comment by AlexBrunetti** [comment]
You wrote the reason, why are you asking? :)

Alex

**Comment by tissatussa** [comment]
mm .. i think the reason the is most engines do a search without a goal .. eg. look at the f6 line (green) of Texel in the first clip : its King does not walk the preferred route because the walking distance is over n ply .. but i guess ShashChess sees this line somehow as 'forced' (i.e. without obstacles) and does the proper pruning .. i'm asking you how Blunder treats the white and black square complexes.

**Comment by algerbrex** [comment]
Hi @tissatussa ! Nice Python script you're developing, looks like it'll be useful for your engine testing tasks :-)

Indeed the position you present is interesting, and even Stockfish seems not to be able to find the path to victory.

As for Blunder, it does no special work with color complexes or the like. For future evaluation improvements, I plan to implement terms like bad/good bishops based on the color complex of both sides' pawns. But currently, Blunder has no knowledge that would be akin to examining color complexes.

I of course can't speak about why each individual engine you present can't find the right path (although it does make me feel better that even very strong engines can't find it, so Blunder isn't alone :-) ), but again, I suspect the issue has to be with pruning and reductions. On the face, f6 doesn't look like a very intuitive or obvious move, especially given the path the king needs to take, so I don't think it's a stretch to think one explanation for some of the engines would be pruning seemingly innocuous king moves.
