### ISSUE TITLE
Draw score because of fifty move rule when it's mate

### ISSUE THREAD

**Issue by Disservin** [algerbrex/blunder#14]
fen: `8/8/2p5/3b1K1k/4p3/4PpR1/5P2/8 w - - 99 113`
```
info depth 42 score cp 0 nodes 2378760 nps 2147718 time 1107 pv g3g7
info depth 43 score cp 0 nodes 1102889 nps 2175235 time 507 pv g3g7
info depth 44 score cp 0 nodes 1191410 nps 2155794 time 552 pv g3g7
info depth 45 score cp 0 nodes 214258 nps 2660628 time 80 pv g3g7
```
The position is mate in 1 (Rh3#) and not a draw, this happens because the mating move also allows draw by fifty move rule, however checkmate overwrites the fifty move rule.

**Comment by algerbrex** [comment]
Hi, thanks for bringing this issue up. I'm working on a bug fix and it should be pushed within a couple of hours.
