### ISSUE TITLE
Can you build a Korean chess engine?

### ISSUE THREAD

**Issue by cjssh1002** [algerbrex/blunder#18]
Can you build a Korean chess engine?

**Comment by algerbrex** [comment]
Hi @cjssh1002 apologies for the late reply, but I'm sure what you mean exactly. If you're asking if I can translate my code to Korean, then I'm afraid not, as I'm just not familiar with Korean. If you'd like to discuss this topic further, feel free to shoot me an email, which you can find under my profile!
