### ISSUE TITLE
UCI option Time-Per-Move ?

### ISSUE THREAD

**Issue by tissatussa** [algerbrex/blunder#9]
i noticed Blunder can not do time-per-move in CuteChess !?  This happens with v6.0.0 and v7.2.0 .. i tested both compiled versions and your assets .. is this UCI option not implemented ?  When i set time-per-whole-game all is OK ..

I'm on Xubuntu 20.04 and CuteChess v1.2.0

**Comment by algerbrex** [comment]
Hi @tissatussa , yes, you are correct. If you're referring to the UCI option "movetime", it's not currently implemented. Thanks for bringing this to my attention again, I'll make sure this is implemented in the next version release of Blunder, which will hopefully be before the end of the year.

**Comment by tissatussa** [comment]
Take your time to implement this.
I would be honoured !

![Using RubiChess in a film · Issue #315 · Matthies_RubiChess - github com - edit](https://user-images.githubusercontent.com/1109281/144260643-d382c522-cb86-4ffd-906f-64848d73cb4a.png)

Oops !

**Comment by algerbrex** [comment]
@tissatussa sure, no problem. I'd like Blunder to be a complete chess engine eventually, and that means supporting all the basics of the UCI protocol. And thanks for the shoutout! But I suppose it was deleted since the repository author may not have considered it in the best taste to promote another engine in that place.

**Comment by tissatussa** [comment]
yeah .. i can IMAGINE that :-)  [ https://www.bitchute.com/video/fQcz6HI6PI2R/ ]

**Comment by algerbrex** [comment]
Hi @tissatussa I've just released a new version where movetime is supported, some I'm closing this issue. Thanks :)
